### ISSUE TITLE
[BUG] weird double seekbar on (at least) youtube

### ISSUE THREAD

**Issue by ANaPhOrAX** [trophygeek/universalvideomaximizer#26] opened 2023-09-21 14:39 UTC
with the new version (on chrome) I'm getting a double seekbar on youtube. the regular one, and then also like a fully red one on top of it, blocking my access to the seekbar. super annoying. I actually had to remove the addon and find a crx for 2.0.20, because it's unworkable. I don't know what supposedly broke anyway because 2.0.20 is working fine for me

**Comment by trophygeek** [comment] 2023-09-21 15:05
Also, you may try quiting/restarting Chrome because of this long standing bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1271154

**Comment by trophygeek** [comment] 2023-09-21 22:15
Oh, and if you have any other extensions that might be running on youtube can you list them (or test disabling them)?

**Comment by ANaPhOrAX** [comment] 2023-09-22 08:27
weirdly when I tried the beta today it didn't do it. what did happen, though, was that the timing/scale(?) on the seekbar was off. don't really know how to phrase it, so here: https://i.imgur.com/2jnwWMl.png

the video is over, but on the seekbar I'm not at the end yet. after I comment this I'll try it again with everything disabled except for uvm and ublock, brb

**Comment by ANaPhOrAX** [comment] 2023-09-22 08:28
okay yeah it still does it with everything else disabled

**Comment by trophygeek** [comment] 2023-09-22 10:29
Thanks for the screenshots!

The original layout issue could have been caused by the upgrade process? I've seen it while testing.

The progress indicator being off I've seen with other sites, so I think I can can produce it. I'll let you know if I can't.

Some "fun" facts with youtube:
- Youtube site has regular mode and "theater mode"  and the youtube page layout is completely different. I have to remember to test them both.
https://i.imgur.com/ICGBjQd.png  vs https://i.imgur.com/dOOqNmP.png

- Sometimes resizing the window fixes the progress position. I try to send updates to the page to trick it into thinking it's been resized, but it's not reliable. Chrome's security stops most "synthetic events"  (think of someone simulating key typing or button clicking from an ad frame.)

Once I can repro the progress position problem, I'll create a new issue and CC you.

**Comment by trophygeek** [comment] 2023-09-23 08:07
Created a new bug:
https://github.com/trophygeek/universalvideomaximizer/issues/29

Going to close this one, assume it's related to Chrome's update-extensions bug.

**Closed by trophygeek** 2023-09-23 08:07 UTC
Labels: bug
