### ISSUE TITLE
[Bug] Subtitles vanish on v3 when expanded video (youtube)

### ISSUE THREAD

**Issue by engineerbaraazakariya** [trophygeek/universalvideomaximizer#32] opened 2023-09-25 18:53 UTC
The video subtitles vanish on universalvideomaximizer extension version 3 when you expand the video even if you choose another language of the subtitle to force the web player to reload the subtitle still the subtitle won't show anymore until you refresh the page or until you re-click on minimize the video back to its original size and even after that the subtitle size will be different

**Comment by trophygeek** [comment] 2023-09-25 20:28
Thanks for reporting!

Is there a site you can give that I can test it with?

**Comment by engineerbaraazakariya** [comment] 2023-09-26 11:11
It is on every streaming website i.e. youtube and any other streaming, here is a video of screen for the bug (only v3):
https://youtu.be/0pIsWojBzow

**Comment by trophygeek** [comment] 2023-09-26 14:21
The video's perfect. This should be enough that I can verify. It may have something to do with right-to-left text, too.

**Comment by trophygeek** [comment] 2023-09-27 14:46
I was not able to reproduce exactly, but I have fix for youtube. I am just waiting for the Chrome Store to update.

Once it's been rolled out, I will follow up to see if this problem better for you.

**Comment by trophygeek** [comment] 2023-09-28 15:01
v3.0.108 is updated in the Chrome Store. There is also an important Chrome security update.
Can you check this bug and let me know if it's better for you?

**Comment by engineerbaraazakariya** [comment] 2023-09-28 15:15
it was only on Macos, and my mbp ssd is now not working due to an in-complete os update (using windows and I installed the extension today and I can see no issue on Windows), I will use my mbp after few days hopefully and I will check this issue if it is still there on my mac the first thing after I have a stable os env again within these few coming days, I will keep you posted, thanks! (may I will close this issue if it is fixed too in that time)

**Comment by trophygeek** [comment] 2023-09-28 15:42
Thank you for checking!

MacOS and Chrome have both recently had security updates. This adds more complexity to testing.

**Comment by engineerbaraazakariya** [comment] 2023-10-01 16:29
I was able to reproduce the same issue on (Chrome, Brave and Brave Nightly) browsers on MacOs Ventura, Catalina and on Windows 11, I thought then it could be related to some (side effect) with some other installed extensions but I tried then removing every single other extension then use incognito mode of Chrome with only this one extension, sorry but the issue was still there, if you could not reproduce it then I am not sure maybe I will go to use the v2 and that is it until someone else has the same possible bug. thanks for responding anyways.
Update:
I re-tried now with V2 and things got back to be perfect again (I still have the subtitles), I will stick there then.

**Comment by trophygeek** [comment] 2023-10-02 02:40
OK. I'll keep trying to reproduce it.

Do you have a link directly to the video that's failing?
Also, what language are you using? I assume it's a right-to-left one?

**Comment by trophygeek** [comment] 2023-10-04 14:31
OK. I removed some aggressive pop-up ^_blocker_ feature from the latest version. It was trying to stop videos from showing ad popups in the middle of playback, but I suspect it was causing a bunch of problems.

You might try the latest version when you get a chance:
https://chrome.google.com/webstore/detail/video-maximizer/cdnlfphfngnfhjcnoikfhaomaaflaiie

**Comment by engineerbaraazakariya** [comment] 2023-10-07 20:07
Sorry it took me sometime until I was able to comment, I don't now have access to MacOs to test the issue again but on I tested on Windows 11 and on Ubuntu where I was also facing this issue in v3.0.0 and I can confirm now that it is solved with the latest for both of these two OS from my side, I will test on Mac in a week after my mac is fixed and now I am using the latest version  of the extension at the time of writing this.
![image](https://github.com/trophygeek/universalvideomaximizer/assets/5383782/dc284675-b2cc-4b95-8089-267203876a6d)

**Comment by trophygeek** [comment] 2023-10-07 21:51
Thank you so much for testing and helping to make Video Maximizer better!

I'm closing this issue for now, we can always reopen it.

**Closed as completed by trophygeek** 2023-10-07 21:51 UTC
Labels: bug
